image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CI_BUILD_USER: magnarox
  USER_GITLAB: capgemini
  APP_NAME: yummy
  REPO: magnarox/yummy

stages:
  - build
  - deploy 

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package -DskipTests" 
  artifacts:
    paths:
      - target/*.jar
      - target/*.sh
      - target/Dockerfile

docker-build:
  stage: deploy 
  script:
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN registry.hub.docker.com
    - cd target
    - docker build -t registry.hub.docker.com/$REPO .
    - docker push registry.hub.docker.com/$REPO 

