spring:
  main:
    web-application-type: none
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:8092
          zk-nodes: localhost
      bindings:
        input:
          binder: kafka
          destination: ner
          source: ner
        output:
          binder: kafka
          destination: ner
format: dd/MM/YYYY hh:mm:ss
fixed-delay: 3000