spring:
  main:
    web-application-type: none
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.71.2.66:8092
          zk-nodes: localhost
      bindings:
        input:
          binder: kafka
          destination: topicjson
        output:
          binder: kafka
          destination: topicjson
format: dd/MM/YYYY hh:mm:ss
fixed-delay: 3000
urlner: http://localhost:9999/opener
urlinsight:  http://localhost:8080/api/
ner:  true
graph:
  enabled: true
  host: localhost
  port: 8090