spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.71.2.66:8092
          zk-nodes: localhost
      bindings:
        input:
          binder: kafka
          destination: topicjson
        output:
          binder: kafka
          destination: topicjson
format: dd/MM/YYYY hh:mm:ss
fixed-delay: 3000
urlner: http://localhost:9999/opener
urlinsight:  http://localhost:8080/api/
ner:  false
graph:
  enabled: true
  host: localhost
  port: 8090
elasticsearch:
  enabled: true
  host: localhost
  clustername: insight
  port: 9200
  node-port: 9300
  index-name: gazetter