version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
        - 2181:2181
        networks:
        - insight
    kafka:
        image: wurstmeister/kafka:latest
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.0.16
            KAFKA_ADVERTISED_PORT: 8092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "ner:1:1"
        ports:
        - 8092:9092
        networks:
        - insight
networks:
    insight:
        driver: bridge
